# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.TextField(blank=True),
        ),
    ]
